### ISSUE TITLE
relocation address error

### ISSUE THREAD

**Issue by nblog** [zyantific/zyan-hook-engine#4]
samlpe:

ZyrexInstallInlineHook((void*)&CopyFileW, (const void*)&callback, &original);

for example: 
kernel32.dll->CopyFileW
nop
nop
nop
jmp $-0xC
![无标题](https://user-images.githubusercontent.com/10218627/72594156-c0e34a00-3941-11ea-8169-239a539f81f1.png)

trampoline->code_buffer :
![无标题](https://user-images.githubusercontent.com/10218627/72594574-a8276400-3942-11ea-804f-bf5054601b3f.png)

jmp 0x7752E597  ; error jmp 

"jmp 0x7752E598"  that's the right jump, It should be a calculation error.

**Comment by nblog** [comment]
[ZyrexCalculateRelativeOffset(length, (ZyanUPointer)address, ](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L581)
address value error.   

maybe like this.
#L568
```
        // Write opcode
        ZyanU8* address = (ZyanU8*)context->destination + context->bytes_written;
        ZyanUPointer ptr = (ZyanUPointer)address;
        if (opcode == 0xE9)
        {
            *address++ = 0xE9;
        } else
        {
            *address++ = 0x0F;
            *address++ = opcode;
        }

        // Write relative offset
        *(ZyanI32*)(address) = 
            ZyrexCalculateRelativeOffset(length, ptr,
                instruction->absolute_target_address);
```

**Comment by flobernd** [comment]
Thanks for reporting. I will have a look later. It’s very possible that the 32-bit hooking is still off a bit because I mainly tested on 64-bit for now. 

A first stable version is expected to be released in the next two weeks.

**Comment by nblog** [comment]
There is a small problem
FF 25 is a relative address in 64-bit mode
FF 25 is an absolute address in 32-bit mode

x86: ff 25 absolute address       jmp [absolute address]
x64: ff 25 relative address         jmp [dest - src - inst_length]

After a rough observation of your code, [#L581](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L581) is the relative address of the calculation. Under 32 bits, this calculation will result in ff 25 rel32  jmp [asbAddress] is error.

reference:
[jmp](https://www.felixcloutier.com/x86/jmp)

**Comment by flobernd** [comment]
@nblog 
I was not able to reproduce the problem on my local branch - but I already made some changes, so it might have been fixed in the meantime.

Probably going to push my local changes on the weekend after some cleaning.

**Comment by nblog** [comment]
I have tested the error still exists
The reason for the error is when you calculate the relative address
[#L581](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L581) ZyrexCalculateRelativeOffset source_address = address
And you were address ++ at [#L572](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L572), and [#L575](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L575) [#L576](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L575).
The calculated relative offset is also wrong
The correct approach should be to save the address once after [#L569](https://github.com/zyantific/zyan-hook-engine/blob/master/src/Relocation.c#L569)

```
        // Write opcode
        ZyanU8* address = (ZyanU8*)context->destination + context->bytes_written;
        ZyanUPointer ptr = (ZyanUPointer)address;
        if (opcode == 0xE9)
        {
            *address++ = 0xE9;
        } else
        {
            *address++ = 0x0F;
            *address++ = opcode;
        }

        // Write relative offset
        *(ZyanI32*)(address) = 
            ZyrexCalculateRelativeOffset(length, ptr,
                instruction->absolute_target_address);
```

**Comment by flobernd** [comment]
Sorry I am busy with work at the moment and had no time to finish my changes. I just pushed my local progress which definitely does not have the problem you describe. Might have other issues tho .. still work in progress.
